name: CI

on: [ push ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Prayer Importer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run Tests
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results ${{ matrix.os }}
          path: build/test-results/**/*.xml
          reporter: java-junit

      - name: Build
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: package

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: Prayer-Importer-${{ matrix.os }}
          path: build/Prayer Importer*